package:
  name: pytools_uibcdf
  version: 0.1

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - natsort

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides some useful python home made tools (functions, pipes and wrappers) useful for the daily work in the uibcdf lab.
  dev_url: https://github.com/uibcdf/PyTools_uibcdf
  doc_url: https://uibcdf.org
